/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avatar.glb 
Author: Z-Anatomy (https://sketchfab.com/Z-Anatomy)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/myology-31b40fd809b14665b93773936d67c52c
Title: Myology
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/avatar.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Object_2.geometry} material={materials['Cartilage.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_6.geometry} material={materials.Suture} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_8.geometry} material={materials.Cartilage} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_13.geometry} material={materials['Ligament.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_14.geometry} material={materials['Muscles.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials['Cartilage.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Suture} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Cartilage} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Cornea.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Fat.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.None} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Cartilage.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Articular_capsule.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['Articular_capsule.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Bone} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Bone} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Cartilage} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Eye.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Ligament.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['Ligament.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials['Muscles.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_237.geometry} material={materials.Teeth} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_240.geometry} material={materials['Tendon.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/avatar.glb')
