"""
Test Groq API Integration - REAL API CALL
==========================================

This script tests the actual Groq API with the provided API key.
"""

import asyncio
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

from ai_engine.zones import get_zone_info
from ai_engine.nudges import generate_nudge, NudgeConfig, Language


async def test_real_groq_api():
    """Test Groq API with real credentials."""
    
    print("="*60)
    print("TESTING GROQ API - REAL API CALL")
    print("="*60)
    print()
    
    # Check if API key is loaded
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print("❌ ERROR: GROQ_API_KEY not found in environment")
        print("Make sure .env file contains GROQ_API_KEY")
        return
    
    print(f"✓ API Key loaded: {api_key[:10]}...{api_key[-5:]}")
    print()
    
    # Test 1: Resting state (GREEN zone)
    print("Test 1: Resting State (GREEN)")
    print("-" * 40)
    zone_info = get_zone_info(86)
    context = {
        "components": {"hr": 90, "hrv": 85, "spo2": 95, "temp": 90},
    }
    
    try:
        nudge = await generate_nudge(zone_info, context=context)
        print(f"Zone: {nudge.zone.upper()}")
        print(f"Generated by: {nudge.generated_by}")
        print(f"Message: {nudge.message}")
        print(f"Action: {nudge.action}")
        print()
        
        if nudge.generated_by == "groq":
            print("✅ SUCCESS: Groq API responded!")
        else:
            print("⚠️  FALLBACK: API call failed, using template")
    except Exception as e:
        print(f"❌ ERROR: {e}")
    
    print()
    
    # Test 2: Post-exercise (ORANGE zone)
    print("Test 2: Post-Exercise State (ORANGE)")
    print("-" * 40)
    zone_info = get_zone_info(41)
    context = {
        "components": {"hr": 30, "hrv": 20, "spo2": 85, "temp": 50},
        "weakest_component": "hrv",
        "weakest_score": 20,
    }
    
    try:
        nudge = await generate_nudge(zone_info, context=context)
        print(f"Zone: {nudge.zone.upper()}")
        print(f"Generated by: {nudge.generated_by}")
        print(f"Message: {nudge.message}")
        print(f"Action: {nudge.action}")
        print()
        
        if nudge.generated_by == "groq":
            print("✅ SUCCESS: Groq API responded!")
        else:
            print("⚠️  FALLBACK: API call failed, using template")
    except Exception as e:
        print(f"❌ ERROR: {e}")
    
    print()
    
    # Test 3: Pidgin language
    print("Test 3: Pidgin Language (YELLOW)")
    print("-" * 40)
    zone_info = get_zone_info(70)
    config = NudgeConfig(language=Language.PIDGIN)
    
    try:
        nudge = await generate_nudge(zone_info, config=config)
        print(f"Zone: {nudge.zone.upper()}")
        print(f"Language: {nudge.language}")
        print(f"Generated by: {nudge.generated_by}")
        print(f"Message: {nudge.message}")
        print()
        
        if nudge.generated_by == "groq":
            print("✅ SUCCESS: Groq API responded with Pidgin!")
        else:
            print("⚠️  FALLBACK: Using Pidgin template")
    except Exception as e:
        print(f"❌ ERROR: {e}")
    
    print()
    print("="*60)
    print("GROQ API TEST COMPLETE")
    print("="*60)


if __name__ == "__main__":
    asyncio.run(test_real_groq_api())
